### ISSUE TITLE
can't login with the latest version of web

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Zeeguu-Web#16]
i see this in the logs:

```
[Fri May 11 09:41:16.111250 2018] [wsgi:error] [pid 23201:tid 140464140576512] [remote 213.127.30.55:57870] Traceback (most recent call last):
[Fri May 11 09:41:16.111282 2018] [wsgi:error] [pid 23201:tid 140464140576512] [remote 213.127.30.55:57870]   File ".../web/zeeguu_web/account/api/api_connection.py", line 50, in _api_call
[Fri May 11 09:41:16.111290 2018] [wsgi:error] [pid 23201:tid 140464140576512] [remote 213.127.30.55:57870]     resp = requests.post(_api_path(path), data=payload, params=params)
[Fri May 11 09:41:16.111297 2018] [wsgi:error] [pid 23201:tid 140464140576512] [remote 213.127.30.55:57870]   File ".../web/zeeguu_web/account/api/api_connection.py", line 37, in _api_path
[Fri May 11 09:41:16.111303 2018] [wsgi:error] [pid 23201:tid 140464140576512] [remote 213.127.30.55:57870]     if zeeguu_path.endswith("/"):
[Fri May 11 09:41:16.111310 2018] [wsgi:error] [pid 23201:tid 140464140576512] [remote 213.127.30.55:57870] AttributeError: 'NoneType' object has no attribute 'endswith'

```

**Comment by mircealungu** [comment]
fixed. problem was a missing ZEEGUU_API.

added an assertion for the existence of that config option in https://github.com/zeeguu-ecosystem/Zeeguu-Web/commit/1f7090cf94db7af58fbc4569fcfe2630977d02bc
